#!/usr/local/bin/python
# -*- Python -*-
import pgp, sys

PacketType={1:'PKEncrypted', 2:'Signature', 5:'PrivKey', 6:'PubKey',
	    8:'Compressed', 9:'Ciphered', 11:'Plaintext', 12:'Trust',
	    13:'UserID', 14:'Comment'}

def ParseString(s, packet={}):
    try:
	while (s!=""):
	    p=pgp.Packet(s)
	    s=s[p.PacketLength:]
	    packet[p.Type]=p
	    if PacketType.has_key(p.Type): typename=PacketType[p.Type]
	    else: typename='Unknown type'
	    print p.Type, typename
    except pgp.PossibleEnd, message:
	pass

import md5
DEK=md5.new('test').digest()

def DumpPacket(p, indent=0):
    if indent>20: return
    while (1):
	packet=pgp.ReadPacket(p, DEK=DEK)
	if packet==None: break
	if PacketType.has_key(packet.Type): typename=PacketType[packet.Type]
	else: typename=''
	sys.stderr.write(' '*indent+str(packet.Type)+' '+typename+'\n')
	if packet.Type in [pgp.CIPHERED, pgp.COMPRESSED]:
	    DumpPacket(packet, indent+4)
	
DumpPacket(sys.stdin)
    



