[project]
license = BSD-2-Clause AND Unlicense
license-files = [ "LICENSE.rst" ]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = ["pycryptodome_test_vectors.*"]
follow_untyped_imports = true
