from types import ModuleType
from typing import Any, Union, Tuple

__all__ = ['GcmMode']

GHashC = Any

class GcmMode(object):
    block_size: int
    nonce: Union[bytes, bytearray, memoryview]
    def __init__(self, factory: ModuleType, key: Union[bytes, bytearray, memoryview], nonce: Union[bytes, bytearray, memoryview], mac_len: int, cipher_params: Any, ghash_c: GHashC) -> None: ...
    def update(self, assoc_data: Union[bytes, bytearray, memoryview]) -> GcmMode: ...
    def encrypt(self, plaintext: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def decrypt(self, ciphertext: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def verify(self, received_mac_tag: Union[bytes, bytearray, memoryview]) -> None: ...
    def hexverify(self, hex_mac_tag: str): ...
    def encrypt_and_digest(self, plaintext: Union[bytes, bytearray, memoryview]) -> Tuple[bytes, bytes]: ...
    def decrypt_and_verify(self, ciphertext: Union[bytes, bytearray, memoryview], received_mac_tag: bytes) -> bytes: ...
