from typing import Union, Any

class ChaCha20Cipher:
    block_size: int
    nonce: bytes

    def __init__(self, key: bytes, nonce: Union[bytes, bytearray, memoryview]) -> None: ...
    def encrypt(self, plaintext: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def decrypt(self, ciphertext: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def seek(self, position: int) -> None: ...

def new(**kwargs: Any) -> ChaCha20Cipher: ...

block_size: int
key_size: int
