from typing import Union, overload

def _HChaCha20(key: bytes | bytearray, nonce: bytes | bytearray) -> bytearray: ...

class ChaCha20Cipher:
    block_size: int
    nonce: bytes

    def __init__(self, key: bytes | bytearray, nonce: bytes | bytearray) -> None: ...
    @overload
    def encrypt(self, plaintext: bytes | bytearray) -> bytes: ...
    @overload
    def encrypt(self, plaintext: bytes | bytearray, output: Union[bytearray, memoryview]) -> None: ...
    @overload
    def decrypt(self, plaintext: bytes | bytearray) -> bytes: ...
    @overload
    def decrypt(self, plaintext: bytes | bytearray, output: Union[bytearray, memoryview]) -> None: ...
    def seek(self, position: int) -> None: ...

def new(key: bytes | bytearray, nonce: bytes | bytearray | None = ...) -> ChaCha20Cipher: ...

block_size: int
key_size: int
