from typing import Callable, Union, Any, Optional

from Crypto.PublicKey.RSA import RsaKey


class PKCS115_Cipher:
    def __init__(self, key: RsaKey, randfunc: Callable) -> None: ...
    def can_encrypt(self) -> bool: ...
    def can_decrypt(self) -> bool: ...
    def encrypt(self, message: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def decrypt(self, ciphertext: Union[bytes, bytearray, memoryview], sentinel: Any) -> bytes: ...

def new(key: Union[bytes, bytearray, memoryview], randfunc: Optional[Callable]=None) -> PKCS115_Cipher: ...
