from typing import Union, Callable

from Crypto.common import HashAlgorithm

from Crypto.PublicKey import RSA


class PKCS1OAEP_Cipher:
    def __init__(self, key: RSA, hashAlgo: HashAlgorithm, mgfunc: Callable, label: Union[bytes, bytearray, memoryview], randfunc: Callable) -> None:...
    def can_encrypt(self) -> bool: ...
    def can_decrypt(self) -> bool: ...
    def encrypt(self, message: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def decrypt(self, ciphertext: Union[bytes, bytearray, memoryview]) -> bytes: ...

def new(key, hashAlgo: HashAlgorithm, mgfunc: Callable, label: bytes, randfunc: Callable) -> PKCS1OAEP_Cipher: ...
