from typing import Callable, Union, Any

from Crypto.PublicKey import RSA


class PKCS115_Cipher:
    def __init__(self, key: RSA, randfunc: Callable) -> None: ...
    def can_encrypt(self) -> bool: ...
    def can_decrypt(self) -> bool: ...
    def encrypt(self, message: Union[bytes, bytearray, memoryview]) -> bytes: ...
    def decrypt(self, ciphertext: Union[bytes, bytearray, memoryview], sentinel: Any) -> bytes: ...

def new(key: Union[bytes, bytearray, memoryview], randfunc: Callable) -> PKCS115_Cipher: ...
