from typing import Union, Any


class BLAKE2s_Hash(object):
    block_size: int
    digest_size: int
    oid: str

    def __init__(self, data: Union[bytes, bytearray, memoryview], key: bytes, digest_bytes: bytes, update_after_digest: bool) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> BLAKE2s_Hash: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def verify(self, mac_tag: Union[bytes, bytearray, memoryview]) -> None: ...
    def hexverify(self, hex_mac_tag: str) -> None: ...
    def new(self, **kwargs: Any) -> BLAKE2s_Hash: ...

def new(**kwargs: Any) -> BLAKE2s_Hash: ...