from typing import Any, Union


class SHA3_224_Hash(object):
    digest_size: int
    oid: str
    def __init__(self, data: Union[ bytes, bytearray, memoryview], update_after_digest: bool) -> None: ...
    def update(self, data: Union[ bytes, bytearray, memoryview]) -> SHA3_224_Hash: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def new(self) -> SHA3_224_Hash: ...

def new(*args: Any, **kwargs: Any) -> SHA3_224_Hash: ...

digest_size: int
