from typing import Any


class BLAKE2b_Hash(object):
    block_size: int
    digest_size: int
    oid: str

    def __init__(self, data: bytes, key: bytes, digest_bytes: bytes, update_after_digest: bool) -> None: ...
    def update(self, data: bytes) -> BLAKE2b_Hash: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def verify(self, mac_tag: bytes) -> None: ...
    def hexverify(self, hex_mac_tag: str) -> None: ...
    def new(self, **kwargs: Any) -> BLAKE2b_Hash: ...

def new(**kwargs: Any) -> BLAKE2b_Hash: ...