from typing import Union, Any


class Keccak_Hash(object):
    digest_size: int
    def __init__(self, data: Union[bytes, bytearray, memoryview], digest_bytes: int, update_after_digest: bool) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> Keccak_Hash: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def new(self, **kwargs: Any) -> Keccak_Hash: ...

def new(**kwargs: Any) -> Keccak_Hash: ...
