from typing import Union, Any


class SHA3_256_Hash(object):
    digest_size: int
    oid:str
    def __init__(self, data: Union[bytes, bytearray, memoryview], update_after_digest: bool) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> SHA3_256_Hash: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def new(self) -> SHA3_256_Hash: ...

def new(*args: Any, **kwargs: Any) -> SHA3_256_Hash: ...

digest_size: int
