from typing import Union, Optional


class SHAKE256_XOF(object):
    oid: str
    def __init__(self, data: Optional[Union[bytes, bytearray, memoryview]]=None) -> None: ...
    def update(self, data: Union[bytes, bytearray, memoryview]) -> SHAKE256_XOF: ...
    def read(self, length: int) -> bytes: ...
    def new(self, data: Optional[Union[bytes, bytearray, memoryview]]=None) -> SHAKE256_XOF: ...

def new(data: Optional[Union[bytes, bytearray, memoryview]]=None) -> SHAKE256_XOF: ...
