from typing import Tuple

def read_int4(data: bytes) -> Tuple[int, bytes]: ...
def read_int8(data: bytes) -> Tuple[int, bytes]: ...
def read_bytes(data: bytes) -> Tuple[bytes, bytes]: ...
def read_string(data: bytes) -> Tuple[str, bytes]: ...
def check_padding(pad: bytes) -> None: ...
def import_openssh_public_cert_generic(data: bytes) -> Tuple[bytes, bytes]: ...
def check_openssh_public_cert_footer(data: bytes) -> None: ...
def import_openssh_private_generic(data: bytes, password: bytes) -> Tuple[str, bytes]: ...
