from typing import Tuple, ByteString, Union, Callable, Generator, Literal, Optional

key = Tuple[Tuple[bytes, bytes], ...]
h = Callable[[ByteString], bytes]
hn = Union[str, h]
sig = Tuple[bytes, ...]

class LamportKey(object):
    def __init__(self, key: key, is_private: bool, h: h, used: bool=False) -> None: ...
    def _sign(self, message: ByteString) -> sig: ...
    def sign(self, message: ByteString) -> sig: ...
    def _verify(self, message: ByteString, signature: sig) -> bool: ...
    def verify(self, message: ByteString, signature: sig) -> bool: ...
    def has_private(self) -> bool: ...
    def publickey(self) -> LamportKey: ...

def generate(size: Optional[int], onewayfunc: Optional[hn])) -> LamportKey: ...
def construct(key: key, is_private: bool, onewayfunc: hn), used: bool=False) -> LamportKey: ...
def _s2p(h: h, key: key) -> key: ...
def _iterbits(data: ByteString) -> Generator[Literal[0, 1], None, None]: ...
