name: Wheels

on:
  push:
    tags:
    - '*'

jobs:
  build_source:
    name: Build source package
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: '3.x'

      - name: Build source package (.tar.gz)
        run: |
          python -m pip install setuptools
          python setup.py sdist

      - uses: actions/upload-artifact@v6
        with:
          name: source-${{ github.ref_name }}
          path: ./dist/*.tar.gz

  build_python3_wheels:
    name: Build Python 3 wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-15, ubuntu-22.04-arm, windows-11-arm]

    if: github.actor == 'Legrandin'

    steps:
      - uses: actions/checkout@v6

      - name: Select architecture for MacOS
        run: |
          echo 'CIBW_ARCHS=x86_64 universal2' >> $GITHUB_ENV
        if: runner.os == 'macOS'

      - uses: pypa/cibuildwheel@v3.3.1
        name: Build wheels
        env:
          # cibuildwheel will build wheel once and test it for each CPython version
          # and for PyPy >= 3.10
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp313t-* cp314-* cp314t-* pp310-* pp311-*"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
          CIBW_MANYLINUX_I686_IMAGE: "manylinux2014"
          CIBW_MANYLINUX_AARCH64_IMAGE: "manylinux2014"
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: "manylinux2014"
          CIBW_MANYLINUX_PYPY_I686_IMAGE: "manylinux2014"
          CIBW_MANYLINUX_PYPY_AARCH64_IMAGE: "manylinux2014"
          CIBW_ENABLE: "cpython-freethreading pypy pypy-eol"
          CIBW_BEFORE_TEST_LINUX: "(ldd /bin/ls | grep -q musl && apk add gmp) || true"

          CIBW_TEST_COMMAND: "python -m Crypto.SelfTest --skip-slow-tests"

      - name: Delete manylinux1 wheels
        if: runner.os == 'Linux'
        run: |
          rm -f wheelhouse/*-manylinux1_*.whl

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-python3-${{ matrix.os }}-${{ github.ref_name }}
          overwrite: true
          path: ./wheelhouse/*.whl
